export const projectKeyMap = {
  id: 'i',
  name: 'n',
  mode: 'm',
  dirty: 'd',
  order: 'o',
  cells: 'c',
  query: 'q',
  sql: 's',
  backend: 'b',
  port: 'po',
  markdown: 'md',
  position: 'p',
  type: 't',
};